# FFNN(Feed forward neural network)


### Defining the network architecture

In [31]:
import numpy as np

# Define the network architecture
input_size = 3  # Number of input features
hidden1_size = 4  # Number of neurons in the first hidden layer
hidden2_size = 3  # Number of neurons in the second hidden layer
output_size = 2  # Number of neurons in the output layer

### Initializing random weights and biases for the layers

In [32]:
# Initialize random weights and biases for the layers
np.random.seed(0)  # For reproducibility

In [33]:
# Initialize weights and biases for the first hidden layer
hidden1_weights = np.random.randn(input_size, hidden1_size)
hidden1_biases = np.random.randn(hidden1_size)

# Initialize weights and biases for the second hidden layer
hidden2_weights = np.random.randn(hidden1_size, hidden2_size)
hidden2_biases = np.random.randn(hidden2_size)

# Initialize weights and biases for the output layer
output_weights = np.random.randn(hidden2_size, output_size)
output_biases = np.random.randn(output_size)

### Output

In [34]:
# You can print the initialized weights and biases if desired
print("First Hidden Layer Weights:")
print(hidden1_weights)
print("First Hidden Layer Biases:")
print(hidden1_biases)
print("Second Hidden Layer Weights:")
print(hidden2_weights)
print("Second Hidden Layer Biases:")
print(hidden2_biases)
print("Output Layer Weights:")
print(output_weights)
print("Output Layer Biases:")
print(output_biases)

First Hidden Layer Weights:
[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]
First Hidden Layer Biases:
[0.76103773 0.12167502 0.44386323 0.33367433]
Second Hidden Layer Weights:
[[ 1.49407907 -0.20515826  0.3130677 ]
 [-0.85409574 -2.55298982  0.6536186 ]
 [ 0.8644362  -0.74216502  2.26975462]
 [-1.45436567  0.04575852 -0.18718385]]
Second Hidden Layer Biases:
[1.53277921 1.46935877 0.15494743]
Output Layer Weights:
[[ 0.37816252 -0.88778575]
 [-1.98079647 -0.34791215]
 [ 0.15634897  1.23029068]]
Output Layer Biases:
[ 1.20237985 -0.38732682]
